version: '3'
services:
  react-docker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-docker
    stdin_open: true
    volumes:
       - ./:/var/www/html/app
       - /var/www/html/app/node_modules